### ISSUE TITLE
BufferedProcessError: Failed to spawn command

### ISSUE THREAD

**Issue by Nunnsy** [AtomLinter/linter-bootlint#21]
Hi there,

I had a quick look at these errors and it might be that it's looking for C:\Users\Daniel.atom\packages\linter-bootlint\node_modules.bin\bootlint in the wrong place?

C:\Users\Daniel.atom\packages\linter-bootlint\node_modules.bin\bootlint
C:\Users\Daniel.atom\packages\linter-bootlint\node_modules\\.bin\bootlint <- Added slash
(odd, when writing the message the slash then full-stop cancelled the slash - could this be occurring in the backend files? I know php syntax works a little like this)

Unsure if this is just a personal system bug. Sorry if it is. Any help would be appreciated :)

```
BufferedProcessError: Failed to spawn command 'C:\Users\Daniel.atom\packages\linter-bootlint\node_modules.bin\bootlint'. Make sure it's a file, not a directory, and it's executable.
BufferedProcessError: Failed to spawn command 'C:\Users\Daniel\.atom\packages\linter-bootlint\node_modules\.bin\bootlint'. Make sure it's a file, not a directory, and it's executable.
    at handleError (C:\Users\Daniel\.atom\packages\linter-bootlint\node_modules\atom-linter\lib\helpers.js:67:26)
    at parameters.exit (C:\Users\Daniel\.atom\packages\linter-bootlint\node_modules\atom-linter\lib\helpers.js:86:13)
    at triggerExitCallback (C:\Users\Daniel\AppData\Local\atom\app-1.4.3\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Daniel\AppData\Local\atom\app-1.4.3\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by Nunnsy** [comment]
My bad, needs jsNode w/ bootlint nmp'd - didn't do this

**Comment by Nunnsy** [comment]
Forget all previous comments sorry - the stack is still as is. I noticed you packaged bootlint so I didn't need to install it through node. Any suggestions? :)

**Comment by Arcanemagus** [comment]
Can you go into the project folder and run `npm install` to ensure it is installed properly?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
