### ISSUE TITLE
Error: /usr/bin/env: ‘node’: No such file or directory

### ISSUE THREAD

**Issue by bkemmer** [AtomLinter/linter-bootlint#92]
Hi, 

I just installed linter-bootlint and I am getting this error bellow:

```
Error: /usr/bin/env: ‘node’: No such file or directory
    at ChildProcess.<anonymous> (/home/kemmer/.atom/packages/linter-bootlint/node_modules/sb-exec/lib/index.js:36:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

```
I tried to reinstall linter and linter-bootlint by using the installation command again (not sure if its the right way).

best regards,
Bruno

**Comment by Arcanemagus** [comment]
Bootlint itself is written rather "odd" and requires Node.js to be installed on your system, even though it is running from within a "node compatible" environment (Atom).

Can you install Node.js and try again?

**Comment by Arcanemagus** [comment]
Marking as closed due to a lack of response.
